// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClassLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class DataTrip
    {
        /// <summary>
        /// Initializes a new instance of the DataTrip class.
        /// </summary>
        public DataTrip() { }

        /// <summary>
        /// Initializes a new instance of the DataTrip class.
        /// </summary>
        public DataTrip(Guid? tripId = default(Guid?), string carType = default(string), int? pickupBorough = default(int?), int? dropoffBorough = default(int?), int? rateCodeId = default(int?), double? fareAmount = default(double?), int? passengerCount = default(int?), int? srFLag = default(int?), int? payType = default(int?), double? tripDistance = default(double?), DateTime? startDate = default(DateTime?), DateTime? endDate = default(DateTime?), TaxiZone pickupTaxiZone = default(TaxiZone), TaxiZone dropOffTaxiZone = default(TaxiZone))
        {
            TripId = tripId;
            CarType = carType;
            PickupBorough = pickupBorough;
            DropoffBorough = dropoffBorough;
            RateCodeId = rateCodeId;
            FareAmount = fareAmount;
            PassengerCount = passengerCount;
            SrFLag = srFLag;
            PayType = payType;
            TripDistance = tripDistance;
            StartDate = startDate;
            EndDate = endDate;
            PickupTaxiZone = pickupTaxiZone;
            DropOffTaxiZone = dropOffTaxiZone;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tripId")]
        public Guid? TripId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "carType")]
        public string CarType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pickupBorough")]
        public int? PickupBorough { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dropoffBorough")]
        public int? DropoffBorough { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rateCodeId")]
        public int? RateCodeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fareAmount")]
        public double? FareAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "passengerCount")]
        public int? PassengerCount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "srFLag")]
        public int? SrFLag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "payType")]
        public int? PayType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tripDistance")]
        public double? TripDistance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "startDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "endDate")]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pickupTaxiZone")]
        public TaxiZone PickupTaxiZone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dropOffTaxiZone")]
        public TaxiZone DropOffTaxiZone { get; set; }

    }
}
