// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace RestClassLibrary.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TaxiZone
    {
        /// <summary>
        /// Initializes a new instance of the TaxiZone class.
        /// </summary>
        public TaxiZone() { }

        /// <summary>
        /// Initializes a new instance of the TaxiZone class.
        /// </summary>
        public TaxiZone(int? locationId = default(int?), string boroughName = default(string), string zone = default(string), string serviceZone = default(string))
        {
            LocationId = locationId;
            BoroughName = boroughName;
            Zone = zone;
            ServiceZone = serviceZone;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public int? LocationId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "boroughName")]
        public string BoroughName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zone")]
        public string Zone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "serviceZone")]
        public string ServiceZone { get; set; }

    }
}
